language: clojure
sudo: false
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler libprotoc-dev
script: lein build-test
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
  - openjdk7
notifications:
  email:
    - oubiwann@gmail.com

